//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdpItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdpItem()
        {
            this.AdpSubscriptions = new HashSet<AdpSubscription>();
        }
    
        public int Id { get; set; }
        public int AdpProductId { get; set; }
        public int AdpCoverageAreaId { get; set; }
        public string NauProdId { get; set; }
        public string Discriminator { get; set; }
    
        public virtual AdpCoverageArea AdpCoverageArea { get; set; }
        public virtual AdpProduct AdpProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdpSubscription> AdpSubscriptions { get; set; }
    }
}
