//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdpSubscription
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int AdpItemId { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string StartupKey { get; set; }
        public string MainActivationKey { get; set; }
        public string BackupActivationKey { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Discriminator { get; set; }
    
        public virtual AdpItem AdpItem { get; set; }
    }
}
