//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Currency()
        {
            this.ValueAddedSubscriptionTypePrices = new HashSet<ValueAddedSubscriptionTypePrice>();
            this.ValueAddedSubscriptionTypes = new HashSet<ValueAddedSubscriptionType>();
        }
    
        public int Id { get; set; }
        public string ShortName { get; set; }
        public string FriendlyName { get; set; }
        public string CurrencySign { get; set; }
        public System.DateTime AddedUtcDate { get; set; }
        public Nullable<System.DateTime> RemovedUtcDate { get; set; }
        public string Discriminator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValueAddedSubscriptionTypePrice> ValueAddedSubscriptionTypePrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValueAddedSubscriptionType> ValueAddedSubscriptionTypes { get; set; }
    }
}
