//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomVersion
    {
        public int CustomVersionID { get; set; }
        public int CustomerID { get; set; }
        public int Version { get; set; }
        public string Description { get; set; }
        public string Discriminator { get; set; }
    }
}
