//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfo
    {
        public int C_ID { get; set; }
        public int C_customerID { get; set; }
        public string C_ShipName { get; set; }
        public int C_NeptuneCode { get; set; }
        public System.DateTime C_InfoDate { get; set; }
        public string Discriminator { get; set; }
    }
}
