//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPermitsPriorToPay
    {
        public int CustomerId { get; set; }
        public int EncCellId { get; set; }
        public int EcdisTypeId { get; set; }
        public Nullable<System.DateTime> ExpiryUtcDate { get; set; }
        public string PermitString { get; set; }
        public Nullable<int> EncOrderId { get; set; }
        public Nullable<System.DateTime> PermitDownloadedUtcDate { get; set; }
        public int PermitStatusId { get; set; }
        public string Discriminator { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual EcdisType EcdisType { get; set; }
        public virtual EncCell EncCell { get; set; }
        public virtual EncOrder EncOrder { get; set; }
        public virtual PermitStatu PermitStatu { get; set; }
    }
}
