//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFS_PendingData
    {
        public int ID { get; set; }
        public string ChartNumber { get; set; }
        public int NMNumber { get; set; }
        public int Year { get; set; }
        public int Week { get; set; }
        public string Path { get; set; }
        public int StartPage { get; set; }
        public Nullable<int> EndPage { get; set; }
        public string Type { get; set; }
        public string Discriminator { get; set; }
    }
}
