//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncCellCustomerPaysAreasHistory
    {
        public int CustomerId { get; set; }
        public int EncCellId { get; set; }
        public System.DateTime UtcAuditDate { get; set; }
        public int PaysAreaStatusId { get; set; }
        public string CustomerServiceTicketId { get; set; }
        public string Discriminator { get; set; }
    }
}
