//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncCell
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncCell()
        {
            this.CustomerPermitsPriorToPays = new HashSet<CustomerPermitsPriorToPay>();
            this.EncCellCustomerPaysAreas = new HashSet<EncCellCustomerPaysArea>();
            this.EncCellCustomerPermits = new HashSet<EncCellCustomerPermit>();
            this.EncCellReplacements = new HashSet<EncCellReplacement>();
            this.EncCellReplacements1 = new HashSet<EncCellReplacement>();
            this.EncCellsInEncProducts = new HashSet<EncCellsInEncProduct>();
            this.EncVersions = new HashSet<EncVersion>();
            this.RequiredEncsForVoyages = new HashSet<RequiredEncsForVoyage>();
            this.RequiredEncsForSharedRoutes = new HashSet<RequiredEncsForSharedRoute>();
        }
    
        public int Id { get; set; }
        public int IssuerId { get; set; }
        public string CellName { get; set; }
        public string Description { get; set; }
        public byte NavigationalPurpose { get; set; }
        public decimal BoundarySLat { get; set; }
        public decimal BoundaryWLon { get; set; }
        public decimal BoundaryNLat { get; set; }
        public decimal BoundaryELon { get; set; }
        public string PolygonPoints { get; set; }
        public short BaseEdition { get; set; }
        public System.DateTime BaseIssueDate { get; set; }
        public Nullable<short> LatestUpdateNumber { get; set; }
        public Nullable<System.DateTime> RecordLastUpdated { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string GeometryData { get; set; }
        public Nullable<System.DateTime> ReleaseDateUtc { get; set; }
        public Nullable<System.DateTime> CancelDateUtc { get; set; }
        public Nullable<System.DateTime> ReplaceDateUtc { get; set; }
        public System.Data.Entity.Spatial.DbGeography Geography { get; set; }
        public Nullable<int> DownloadedBaseEdition { get; set; }
        public Nullable<int> DownloadedUpdateNumber { get; set; }
        public Nullable<System.DateTime> DownloadedUtcDate { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Geometry { get; set; }
        public Nullable<int> DownloadedIhoBaseEdition { get; set; }
        public Nullable<int> DownloadedIhoUpdateNumber { get; set; }
        public Nullable<System.DateTime> DownloadedIhoUtcDate { get; set; }
        public bool IsForSale { get; set; }
        public string Discriminator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPermitsPriorToPay> CustomerPermitsPriorToPays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncCellCustomerPaysArea> EncCellCustomerPaysAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncCellCustomerPermit> EncCellCustomerPermits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncCellReplacement> EncCellReplacements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncCellReplacement> EncCellReplacements1 { get; set; }
        public virtual issuer issuer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncCellsInEncProduct> EncCellsInEncProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncVersion> EncVersions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequiredEncsForVoyage> RequiredEncsForVoyages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequiredEncsForSharedRoute> RequiredEncsForSharedRoutes { get; set; }
    }
}
