//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncFileInfo
    {
        public int Id { get; set; }
        public string CellName { get; set; }
        public Nullable<short> EDTN { get; set; }
        public Nullable<short> UPDN { get; set; }
        public string FileName { get; set; }
        public string BlobStorageFilePath { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public Nullable<int> IssuerId { get; set; }
        public string CountryCode { get; set; }
        public string Discriminator { get; set; }
    
        public virtual issuer issuer { get; set; }
    }
}
