//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncOrdersHistory
    {
        public int Id { get; set; }
        public System.DateTime UtcAuditDate { get; set; }
        public int EncOrderTypeId { get; set; }
        public int IssuersEncOrderHeaderId { get; set; }
        public Nullable<System.DateTime> ExpiryUtcDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int EncOrderStatusId { get; set; }
        public int EncProductId { get; set; }
        public string Discriminator { get; set; }
    }
}
