//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncOrder()
        {
            this.CustomerPermitsPriorToPays = new HashSet<CustomerPermitsPriorToPay>();
            this.EncCellCustomerPermits = new HashSet<EncCellCustomerPermit>();
        }
    
        public int Id { get; set; }
        public int EncOrderTypeId { get; set; }
        public int IssuersEncOrderHeaderId { get; set; }
        public Nullable<System.DateTime> ExpiryUtcDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int EncOrderStatusId { get; set; }
        public int EncProductId { get; set; }
        public bool IsPaysPlus { get; set; }
        public string Discriminator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPermitsPriorToPay> CustomerPermitsPriorToPays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncCellCustomerPermit> EncCellCustomerPermits { get; set; }
        public virtual EncOrderStatu EncOrderStatu { get; set; }
        public virtual EncOrderType EncOrderType { get; set; }
        public virtual EncProduct EncProduct { get; set; }
        public virtual IssuersEncOrderHeader IssuersEncOrderHeader { get; set; }
    }
}
