//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncProductPrice
    {
        public int EncProductId { get; set; }
        public int EncOrderTypeId { get; set; }
        public System.DateTime ValidFromUtcDate { get; set; }
        public Nullable<System.DateTime> ValidToUtcDateTo { get; set; }
        public decimal Price { get; set; }
        public string Discriminator { get; set; }
    
        public virtual EncOrderType EncOrderType { get; set; }
        public virtual EncProduct EncProduct { get; set; }
    }
}
