//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncProduct()
        {
            this.EncCellsInEncProducts = new HashSet<EncCellsInEncProduct>();
            this.EncOrders = new HashSet<EncOrder>();
            this.EncProductPrices = new HashSet<EncProductPrice>();
            this.FrequentlyUsedEncProducts = new HashSet<FrequentlyUsedEncProduct>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ValidLicensePeriod { get; set; }
        public bool IsForSale { get; set; }
        public int EncProductTypeId { get; set; }
        public int IssuerId { get; set; }
        public int CountryId { get; set; }
        public int PriceBand { get; set; }
        public string Discriminator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncCellsInEncProduct> EncCellsInEncProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncOrder> EncOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncProductPrice> EncProductPrices { get; set; }
        public virtual EncProductType EncProductType { get; set; }
        public virtual issuer issuer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrequentlyUsedEncProduct> FrequentlyUsedEncProducts { get; set; }
    }
}
