//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class errorlog
    {
        public long C_Id { get; set; }
        public Nullable<System.DateTime> C_Added { get; set; }
        public string C_Where { get; set; }
        public string C_What { get; set; }
        public string Discriminator { get; set; }
    }
}
