//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImoPublicationCorrection
    {
        public int Id { get; set; }
        public string ProdId { get; set; }
        public int CorrectionDocId { get; set; }
        public Nullable<int> Volume { get; set; }
        public int PublicationStartPage { get; set; }
        public int PublicationEndPage { get; set; }
        public int CorrectionStartPage { get; set; }
        public int CorrectionEndPage { get; set; }
        public int PublicationActualStartPage { get; set; }
        public int PublicationActualEndPage { get; set; }
        public string Discriminator { get; set; }
    
        public virtual PublicationCorrectionDocument PublicationCorrectionDocument { get; set; }
    }
}
