//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InmarsatProviderHistory
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public short Region { get; set; }
        public string DNID { get; set; }
        public string MemberNumber { get; set; }
        public string TerminalId { get; set; }
        public string PollInterval { get; set; }
        public System.DateTime AuditUtcDate { get; set; }
        public string Discriminator { get; set; }
    }
}
