//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuersEncOrderHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IssuersEncOrderHeader()
        {
            this.EncOrders = new HashSet<EncOrder>();
        }
    
        public int Id { get; set; }
        public int EncOrderHeaderId { get; set; }
        public int IssuerId { get; set; }
        public string OrderId { get; set; }
        public string CorrelationId { get; set; }
        public int IssuersEncOrderHeaderStatusId { get; set; }
        public Nullable<System.DateTime> CanPlaceOrderUtcDate { get; set; }
        public string Discriminator { get; set; }
    
        public virtual EncOrderHeader EncOrderHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncOrder> EncOrders { get; set; }
        public virtual issuer issuer { get; set; }
        public virtual IssuersEncOrderHeaderStatu IssuersEncOrderHeaderStatu { get; set; }
    }
}
