//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuersEncOrderHeadersHistory
    {
        public int Id { get; set; }
        public System.DateTime UtcAuditDate { get; set; }
        public int EncOrderHeaderId { get; set; }
        public int IssuerId { get; set; }
        public string OrderId { get; set; }
        public int IssuersEncOrderHeaderStatusId { get; set; }
        public Nullable<System.DateTime> CanPlaceOrderUtcDate { get; set; }
        public string Discriminator { get; set; }
    }
}
