//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuersAvailableToCustomer
    {
        public Nullable<int> IssuerId { get; set; }
        public Nullable<int> CustomerGroupId { get; set; }
        public int Id { get; set; }
        public string Discriminator { get; set; }
    
        public virtual issuer issuer { get; set; }
    }
}
