//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_sentfiles
    {
        public long C_id { get; set; }
        public int C_customerID { get; set; }
        public Nullable<long> C_ntmID { get; set; }
        public Nullable<int> C_optfileID { get; set; }
        public string C_filename { get; set; }
        public bool C_sentasemail { get; set; }
        public System.DateTime C_requesttime { get; set; }
        public string Discriminator { get; set; }
    }
}
