//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEntry
    {
        public int LogEntryID { get; set; }
        public int ServerID { get; set; }
        public int LogLevel { get; set; }
        public string Entry { get; set; }
        public bool Handled { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string HandledBy { get; set; }
        public Nullable<System.DateTime> HandledAt { get; set; }
        public Nullable<bool> IsPending { get; set; }
        public string Comment { get; set; }
        public string Discriminator { get; set; }
    
        public virtual Server Server { get; set; }
    }
}
