//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarpolData
    {
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public string CategoryFriendlyName { get; set; }
        public string RegionName { get; set; }
        public string RegionFriendlyName { get; set; }
        public string RegionDisplayName { get; set; }
        public string FileName { get; set; }
        public string FileNameWithBlobPath { get; set; }
        public System.DateTime AddedUtcDate { get; set; }
        public Nullable<System.DateTime> LastDownloadUtcDate { get; set; }
        public Nullable<System.DateTime> RemovedUtcDate { get; set; }
        public string Comment { get; set; }
        public string Discriminator { get; set; }
    }
}
