//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaviTabBackupServerInformation
    {
        public int Id { get; set; }
        public int CustomerInfoId { get; set; }
        public int BackupId { get; set; }
        public string ServerHost { get; set; }
        public Nullable<int> ServerPort { get; set; }
        public string AuthKey { get; set; }
        public string VesselName { get; set; }
        public string CatalogPackageFolder { get; set; }
        public string CustomerId { get; set; }
        public string DeviceSerialNumber { get; set; }
        public Nullable<int> DeviceNumber { get; set; }
        public string HardwareId { get; set; }
        public Nullable<int> Timeout { get; set; }
        public string RetryInterval { get; set; }
        public Nullable<int> IsNaviTabAutoUpgradeOn { get; set; }
        public Nullable<System.DateTime> NaviTabAutoUpgradeCheckDate { get; set; }
        public Nullable<int> UnorderedSearchResultCount { get; set; }
        public string Discriminator { get; set; }
    
        public virtual NaviTabBackupCustomerInfo NaviTabBackupCustomerInfo { get; set; }
    }
}
