//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaviTabBackupPdfAttachment
    {
        public int Id { get; set; }
        public int CustomerInfoId { get; set; }
        public int BackupId { get; set; }
        public Nullable<int> LastViewedPage { get; set; }
        public Nullable<int> LastUsedToolType { get; set; }
        public Nullable<int> LastUsedLayout { get; set; }
        public string LastUsedAnnotationColor { get; set; }
        public string LastUsedHighlightColor { get; set; }
        public Nullable<double> LastUsedZoomLevel { get; set; }
        public Nullable<int> IsInkToolAsBrush { get; set; }
        public string AnnotationXml { get; set; }
        public string BookmarkText { get; set; }
        public string BookmarkTextXml { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> PublicaitonId { get; set; }
        public Nullable<int> PublicationDocId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string NauProdId { get; set; }
        public string ProdId { get; set; }
        public string Discriminator { get; set; }
        public string FileName { get; set; }
    
        public virtual NaviTabBackupCustomerInfo NaviTabBackupCustomerInfo { get; set; }
    }
}
