//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaviTabBackupNaviTabInformation
    {
        public int Id { get; set; }
        public int CustomerInfoId { get; set; }
        public int BackupId { get; set; }
        public Nullable<System.DateTime> DateInstalled { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Discriminator { get; set; }
    
        public virtual NaviTabBackupCustomerInfo NaviTabBackupCustomerInfo { get; set; }
    }
}
