//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaviLogLogBookRecord
    {
        public int Id { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int LogBookId { get; set; }
        public int SectionId { get; set; }
        public string CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedById { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string Entry { get; set; }
        public int Status { get; set; }
        public float DoneAtLatitude { get; set; }
        public float DoneAtLongitude { get; set; }
        public string Discriminator { get; set; }
        public string SearchText { get; set; }
    }
}
