//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaviTabBackupPendingDownload
    {
        public int Id { get; set; }
        public int CustomerInfoId { get; set; }
        public int BackupId { get; set; }
        public string SessionKey { get; set; }
        public string PackageKey { get; set; }
        public string ServerHost { get; set; }
        public Nullable<int> ServerPort { get; set; }
        public Nullable<int> NumberOfFilesDownloaded { get; set; }
        public Nullable<long> DownloadSize { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public string Discriminator { get; set; }
    
        public virtual NaviTabBackupCustomerInfo NaviTabBackupCustomerInfo { get; set; }
    }
}
