//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaviTabBackupCorrection
    {
        public int Id { get; set; }
        public Nullable<int> CustomerInfoId { get; set; }
        public int BackupId { get; set; }
        public int PublicaitonDocumentId { get; set; }
        public int CorrectionDocStartPage { get; set; }
        public int CorrectionDocEndPage { get; set; }
        public int OriginalDocStartPage { get; set; }
        public int OriginalDocEndPage { get; set; }
        public int Volume { get; set; }
        public string Discriminator { get; set; }
    
        public virtual NaviTabBackupCustomerInfo NaviTabBackupCustomerInfo { get; set; }
    }
}
