//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaviLogUserInfo
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> AutoLoggedInEnabled { get; set; }
        public string Designation { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsAdministrator { get; set; }
        public Nullable<bool> IsAllowedToOrder { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> RememberMe { get; set; }
        public string UserName { get; set; }
        public string ApplicationConfiguration { get; set; }
        public int CustomerId { get; set; }
        public int DeviceNumber { get; set; }
        public string Discriminator { get; set; }
    }
}
