//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaviTabBackupEReaderUser
    {
        public int Id { get; set; }
        public int CustomerInfoId { get; set; }
        public int BackupId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Designation { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public Nullable<int> RememberMe { get; set; }
        public Nullable<int> AutoLoggedInEnabled { get; set; }
        public Nullable<int> IsAdministrator { get; set; }
        public Nullable<int> IsAllowedToOrder { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string Discriminator { get; set; }
    
        public virtual NaviTabBackupCustomerInfo NaviTabBackupCustomerInfo { get; set; }
    }
}
