//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NeptuneVesselIncrementalReports_Old
    {
        public int ID { get; set; }
        public int CustomerId { get; set; }
        public string ReportData { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public int ReportType { get; set; }
        public string Discriminator { get; set; }
    }
}
