//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class nept2_server
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public byte type { get; set; }
        public string program { get; set; }
        public string value { get; set; }
        public string server { get; set; }
        public string Discriminator { get; set; }
    }
}
