//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neptune_Files
    {
        public long id { get; set; }
        public string sessionid { get; set; }
        public System.DateTime starttime { get; set; }
        public Nullable<System.DateTime> finishtime { get; set; }
        public string ip { get; set; }
        public string file_name { get; set; }
        public Nullable<long> file_size { get; set; }
        public string customer { get; set; }
        public string Discriminator { get; set; }
    }
}
