//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class nept2_files
    {
        public int id { get; set; }
        public string sessionid { get; set; }
        public System.DateTime start { get; set; }
        public Nullable<System.DateTime> finished { get; set; }
        public string ip { get; set; }
        public int customer { get; set; }
        public string filename { get; set; }
        public int filesize { get; set; }
        public int resumefrom { get; set; }
        public string Discriminator { get; set; }
    }
}
