//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ntm_JP
    {
        public int ID { get; set; }
        public int NMNumber { get; set; }
        public Nullable<int> Week { get; set; }
        public int Year { get; set; }
        public string ChartNumber { get; set; }
        public int StartPage { get; set; }
        public int EndPage { get; set; }
        public string LastNtm { get; set; }
        public string DocumentPath { get; set; }
        public string TracingsPath { get; set; }
        public string Type { get; set; }
        public int IssuerID { get; set; }
        public Nullable<System.DateTime> Published { get; set; }
        public System.DateTime Added { get; set; }
        public string Discriminator { get; set; }
    }
}
