//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionalFile
    {
        public int C_Id { get; set; }
        public string C_Type { get; set; }
        public string C_Number { get; set; }
        public string C_NauProdID { get; set; }
        public string C_Path { get; set; }
        public int C_Week { get; set; }
        public int C_Year { get; set; }
        public string C_Page { get; set; }
        public System.DateTime C_Added { get; set; }
        public bool C_Active { get; set; }
        public int C_IssuerID { get; set; }
        public string C_EndPage { get; set; }
        public string Discriminator { get; set; }
    }
}
