//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int Id { get; set; }
        public int OrderHeaderId { get; set; }
        public int ProductGroupId { get; set; }
        public string ProductReference { get; set; }
        public int IssuerId { get; set; }
        public byte OrderStatusId { get; set; }
        public string Comments { get; set; }
        public string Discriminator { get; set; }
        public string ProdId { get; set; }
    
        public virtual issuer issuer { get; set; }
        public virtual OrderHeader OrderHeader { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
    }
}
