//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageOpen
    {
        public int SessionID { get; set; }
        public int PackageID { get; set; }
        public int PackageOpensID { get; set; }
        public string Discriminator { get; set; }
    
        public virtual Package1 Package { get; set; }
        public virtual Session1 Session { get; set; }
    }
}
