//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package1()
        {
            this.PackageOpens = new HashSet<PackageOpen>();
        }
    
        public int PackageID { get; set; }
        public int SessionID { get; set; }
        public long Size { get; set; }
        public long SizeSaved { get; set; }
        public int FileCount { get; set; }
        public int NtmCount { get; set; }
        public int OptionalFilesCount { get; set; }
        public int CopiedCount { get; set; }
        public int CreatedCount { get; set; }
        public int ZippedCount { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string PackageKey { get; set; }
        public string Arguments { get; set; }
        public string PackageInfo { get; set; }
        public bool IsError { get; set; }
        public bool IsTransferred { get; set; }
        public string Discriminator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageOpen> PackageOpens { get; set; }
        public virtual Session1 Session { get; set; }
    }
}
