//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class package
    {
        public int pid { get; set; }
        public Nullable<int> sid { get; set; }
        public string status { get; set; }
        public string arguments { get; set; }
        public Nullable<int> size { get; set; }
        public Nullable<int> files { get; set; }
        public Nullable<int> ntms { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string pkey { get; set; }
        public string Discriminator { get; set; }
    }
}
