//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class poseidon_session
    {
        public int sid { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<long> ip { get; set; }
        public Nullable<long> start { get; set; }
        public Nullable<long> action { get; set; }
        public string request { get; set; }
        public string useragent { get; set; }
        public string Discriminator { get; set; }
    }
}
