//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class poseidon_flag
    {
        public int id { get; set; }
        public int flag { get; set; }
        public int n1 { get; set; }
        public int n2 { get; set; }
        public int userid { get; set; }
        public int position { get; set; }
        public string Discriminator { get; set; }
    }
}
