//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class poseidon_custom_userinformation
    {
        public int id { get; set; }
        public Nullable<int> customerid { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string Discriminator { get; set; }
    }
}
