//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class prefixtable
    {
        public int id { get; set; }
        public string C_Prefix { get; set; }
        public string C_IssuerPrefix { get; set; }
        public string C_Type { get; set; }
        public string C_Description { get; set; }
        public string Discriminator { get; set; }
    }
}
