//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimarSubscriptionType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int PeriodInMonths { get; set; }
        public bool RealTimeEnc { get; set; }
        public bool AutoRenewal { get; set; }
        public Nullable<int> EncOrderTypeId { get; set; }
        public string Discriminator { get; set; }
    
        public virtual EncOrderType EncOrderType { get; set; }
    }
}
