//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicationCorrectionDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PublicationCorrectionDocument()
        {
            this.ImoPublicationCorrections = new HashSet<ImoPublicationCorrection>();
        }
    
        public int Id { get; set; }
        public string PubProductId { get; set; }
        public int IssuerId { get; set; }
        public string CorrectionTitle { get; set; }
        public string Language { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> CorrectionDateUtc { get; set; }
        public System.DateTime AddedDateUtc { get; set; }
        public Nullable<System.DateTime> MappedDateUtc { get; set; }
        public string Discriminator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImoPublicationCorrection> ImoPublicationCorrections { get; set; }
        public virtual issuer issuer { get; set; }
    }
}
