//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicationDocument
    {
        public long Id { get; set; }
        public string NauProdId { get; set; }
        public string ProdId { get; set; }
        public string RelativePath { get; set; }
        public Nullable<int> MaxPrintCount { get; set; }
        public string Password { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<long> FileSize { get; set; }
        public Nullable<int> MaxPercentagePrintAllowed { get; set; }
        public Nullable<int> ProductGroupId { get; set; }
        public string Discriminator { get; set; }
        public string JsonString { get; set; }
    
        public virtual NaviLogPublicationDocumentDetail NaviLogPublicationDocumentDetail { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
    }
}
