//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class rssNew
    {
        public int C_ID { get; set; }
        public string C_Publisher { get; set; }
        public string C_Category { get; set; }
        public string C_Region { get; set; }
        public string C_rssURL { get; set; }
        public string C_Content { get; set; }
        public string C_FeedFileName { get; set; }
        public Nullable<System.DateTime> C_Updated { get; set; }
        public System.DateTime C_Added { get; set; }
        public bool C_Active { get; set; }
        public System.DateTime C_ActiveChanged { get; set; }
        public string Discriminator { get; set; }
    }
}
