//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class session
    {
        public int sid { get; set; }
        public string skey { get; set; }
        public Nullable<int> customer { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<bool> admin { get; set; }
        public Nullable<int> encryptionfile { get; set; }
        public Nullable<bool> mail { get; set; }
        public string server { get; set; }
        public string Discriminator { get; set; }
    }
}
