//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class session_details
    {
        public int id { get; set; }
        public Nullable<int> sid { get; set; }
        public Nullable<short> type { get; set; }
        public Nullable<short> state { get; set; }
        public string value { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string Discriminator { get; set; }
    }
}
