//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TankedPublicationInfo
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string DeviceSerialNumber { get; set; }
        public string NauProdId { get; set; }
        public string ProdId { get; set; }
        public byte[] Salt { get; set; }
        public byte[] RandomString { get; set; }
        public int Iteration { get; set; }
        public Nullable<System.DateTime> TankedOn { get; set; }
        public string FileName { get; set; }
        public string Discriminator { get; set; }
    }
}
