//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int TransferID { get; set; }
        public int SessionID { get; set; }
        public long Size { get; set; }
        public int FileCount { get; set; }
        public long Speed { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsFaulted { get; set; }
        public string Discriminator { get; set; }
    
        public virtual Session1 Session { get; set; }
    }
}
