//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class USCatalog
    {
        public int Id { get; set; }
        public string ProdId { get; set; }
        public string NauProdId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ISBN { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> MediaTypeId { get; set; }
        public string Discriminator { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Language Language { get; set; }
        public virtual MediaType MediaType { get; set; }
    }
}
