//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class USCorrection
    {
        public long Id { get; set; }
        public string ChartNumber { get; set; }
        public string IntlChartNumber { get; set; }
        public Nullable<short> ChartEdition { get; set; }
        public string ChartEditionDate { get; set; }
        public string LastNm { get; set; }
        public short Year { get; set; }
        public byte Week { get; set; }
        public bool IsOriginalUSSource { get; set; }
        public bool IsTemporary { get; set; }
        public bool IsPreliminary { get; set; }
        public bool IsLimitedDistribution { get; set; }
        public bool IsMetricOnly { get; set; }
        public bool IsNewChart { get; set; }
        public bool IsNewEdition { get; set; }
        public string Source { get; set; }
        public string Entries { get; set; }
        public string TracingsPath { get; set; }
        public string BlocksPath { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string Discriminator { get; set; }
    }
}
