//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValueAddedSubscriptionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ValueAddedSubscriptionType()
        {
            this.ValueAddedSubscriptions = new HashSet<ValueAddedSubscription>();
            this.ValueAddedSubscriptionTypePrices = new HashSet<ValueAddedSubscriptionTypePrice>();
        }
    
        public int Id { get; set; }
        public string TypeName { get; set; }
        public string FriendlyName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public System.DateTime AddedUtcDate { get; set; }
        public Nullable<System.DateTime> RemovedUtcDate { get; set; }
        public int ActiveCurrencyId { get; set; }
        public string Discriminator { get; set; }
    
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValueAddedSubscription> ValueAddedSubscriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValueAddedSubscriptionTypePrice> ValueAddedSubscriptionTypePrices { get; set; }
    }
}
