//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValueAddedSubscription
    {
        public int Id { get; set; }
        public int TypeId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime AddedUtcDate { get; set; }
        public Nullable<System.DateTime> RemovedUtcDate { get; set; }
        public bool IsPending { get; set; }
        public string Comment { get; set; }
        public string Discriminator { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ValueAddedSubscriptionStatu ValueAddedSubscriptionStatu { get; set; }
        public virtual ValueAddedSubscriptionType ValueAddedSubscriptionType { get; set; }
    }
}
