//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValueAddedSubscriptionTypePrice
    {
        public int Id { get; set; }
        public decimal Price { get; set; }
        public System.DateTime ValidFromUtcDate { get; set; }
        public Nullable<System.DateTime> ValidToUtcDate { get; set; }
        public int VASTypeId { get; set; }
        public Nullable<int> BaseCurrencyId { get; set; }
        public string Discriminator { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual ValueAddedSubscriptionType ValueAddedSubscriptionType { get; set; }
    }
}
