//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VesselCompanyFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VesselCompanyFile()
        {
            this.VesselCompanyFileAccesses = new HashSet<VesselCompanyFileAccess>();
        }
    
        public int FileId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public int GroupId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Language { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Currency { get; set; }
        public string NauProdId { get; set; }
        public string ProdId { get; set; }
        public string FileName { get; set; }
        public long FileSize { get; set; }
        public string ThumbnailName { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<int> MaxPrintCount { get; set; }
        public Nullable<int> MaxPercentagePrintAllowed { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> MediaTypeId { get; set; }
        public string OriginalFileName { get; set; }
        public string OriginalThumbnailName { get; set; }
        public string Discriminator { get; set; }
    
        public virtual Language Language1 { get; set; }
        public virtual MediaType MediaType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VesselCompanyFileAccess> VesselCompanyFileAccesses { get; set; }
        public virtual VesselCompanyFileType VesselCompanyFileType { get; set; }
        public virtual VesselCompanyPublicationCategory VesselCompanyPublicationCategory { get; set; }
    }
}
