//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoyageRoute
    {
        public int Id { get; set; }
        public decimal Lat { get; set; }
        public decimal Lng { get; set; }
        public int VoyageId { get; set; }
        public string Discriminator { get; set; }
    
        public virtual Voyage Voyage { get; set; }
    }
}
