//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WB_Pending
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string StartPage { get; set; }
        public string EndPage { get; set; }
        public int Section { get; set; }
        public string Discriminator { get; set; }
    }
}
