//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOWWithReporitoryPattern.ClassDiagram_SFNeptuneServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class XmlNTMData
    {
        public long C_Id { get; set; }
        public string C_PrimaryKey { get; set; }
        public Nullable<System.DateTime> C_PubDate { get; set; }
        public int C_IssuerID { get; set; }
        public string C_Type { get; set; }
        public int C_Week { get; set; }
        public int C_NMNumber { get; set; }
        public int C_Year { get; set; }
        public string C_ChartNumber { get; set; }
        public Nullable<int> C_areacode { get; set; }
        public string C_region { get; set; }
        public string C_sub_region { get; set; }
        public string C_vicinities { get; set; }
        public string C_feature_types { get; set; }
        public string C_light_list { get; set; }
        public string C_authority { get; set; }
        public string C_note { get; set; }
        public int C_Ident { get; set; }
        public string C_FolioNumber { get; set; }
        public Nullable<int> C_LastUpdateNM { get; set; }
        public Nullable<System.DateTime> C_LastUpdateDate { get; set; }
        public byte[] C_XML { get; set; }
        public string C_GraphicsPath { get; set; }
        public string C_LowresPath { get; set; }
        public string C_SuperLowresPath { get; set; }
        public Nullable<bool> C_NewEdition { get; set; }
        public System.DateTime C_Added { get; set; }
        public Nullable<bool> C_Original { get; set; }
        public string C_radio_list { get; set; }
        public string Discriminator { get; set; }
    }
}
